import { COLORS } from "@/constants/colors";
import { TYPOGRAPHY } from "@/constants/typography";
import { StyleSheet, type TextStyle } from "react-native";

const styles = StyleSheet.create({
    container: {
        paddingBottom: 40,
        backgroundColor: COLORS.background,
    },
    scrollViewStyle: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    header: {
        paddingHorizontal: 20,
        paddingTop: 24,
        paddingBottom: 16,
    },
    title: {
        ...(TYPOGRAPHY.h1 as TextStyle),
        color: COLORS.text,
        fontSize: 28,
    },
    subtitle: {
        ...(TYPOGRAPHY.bodySmall as TextStyle),
        color: COLORS.textLight,
        marginTop: 4,
    },
    sectionCard: {
        backgroundColor: COLORS.white,
        borderRadius: 24,
        padding: 20,
        marginHorizontal: 16,
        marginBottom: 16,
        shadowColor: "rgba(0,0,0,0.05)",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 1,
        shadowRadius: 12,
        elevation: 2,
    },
    sectionTitle: {
        ...(TYPOGRAPHY.label as TextStyle),
        fontSize: 16,
        color: COLORS.text,
        marginBottom: 16,
        fontWeight: "700",
    },
    formGroup: {
        marginBottom: 20,
    },
    label: {
        ...(TYPOGRAPHY.caption as TextStyle),
        marginBottom: 8,
        color: COLORS.textLight,
        fontSize: 11,
        letterSpacing: 0.5,
    },
    inputContainer: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#F8F9FA",
        borderRadius: 14,
        paddingHorizontal: 14,
        height: 52,
    },
    inputIcon: {
        marginRight: 12,
    },
    input: {
        flex: 1,
        height: "100%",
        ...(TYPOGRAPHY.bodySmall as TextStyle),
        color: COLORS.text,
        fontSize: 15,
    },
    textArea: {
        backgroundColor: "#F8F9FA",
        borderRadius: 14,
        padding: 14,
        height: 120,
        ...(TYPOGRAPHY.bodySmall as TextStyle),
        color: COLORS.text,
        fontSize: 15,
        textAlignVertical: 'top',
    },
    checkBoxContainer: {
        flexDirection: "row",
        flexWrap: 'wrap',
        gap: 12,
        marginTop: 4,
    },
    checkBoxItem: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#F8F9FA",
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 10,
        minWidth: '45%',
    },
    checkboxLabel: {
        marginLeft: 8,
        ...(TYPOGRAPHY.bodySmall as TextStyle),
        color: COLORS.text,
        fontSize: 14,
    },
    radioItemFee: {
        flex: 1,
    },
    inputContainerFee: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#F8F9FA",
        borderRadius: 14,
        paddingHorizontal: 14,
        height: 52,
        marginTop: 8,
    },
    button: {
        backgroundColor: COLORS.primary,
        borderRadius: 16,
        height: 56,
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        marginHorizontal: 16,
        marginTop: 8,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 6,
    },
    buttonText: {
        ...(TYPOGRAPHY.label as TextStyle),
        color: COLORS.white,
        fontSize: 17,
        fontWeight: "700",
    },

    // IMAGE PICKER STYLES
    imagePickerBlock: {
        gap: 12,
    },
    imagePicker: {
        width: "100%",
        height: 200,
        backgroundColor: "#F8F9FA",
        borderRadius: 14,
        overflow: "hidden",
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#E9ECEF",
        borderStyle: 'dashed',
    },
    previewImageContainer: {
        width: "100%",
        height: "100%",
        position: 'relative',
    },
    previewImage: {
        width: "100%",
        height: "100%",
    },
    removeImageButton: {
        position: "absolute",
        top: 12,
        right: 12,
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: "rgba(0, 0, 0, 0.6)",
        justifyContent: "center",
        alignItems: "center",
    },
    placeholderContainer: {
        alignItems: "center",
        gap: 8,
    },
    placeholderText: {
        ...(TYPOGRAPHY.bodySmall as TextStyle),
        color: COLORS.textLight,
        fontSize: 14,
    },
    imageResizeControls: {
        flexDirection: "row",
        backgroundColor: "#F1F3F5",
        borderRadius: 12,
        padding: 4,
        gap: 4,
    },
    imageResizeOption: {
        flex: 1,
        height: 36,
        borderRadius: 8,
        justifyContent: "center",
        alignItems: "center",
    },
    imageResizeOptionSelected: {
        backgroundColor: COLORS.white,
        shadowColor: "rgba(0,0,0,0.1)",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 1,
        shadowRadius: 4,
        elevation: 2,
    },
    imageResizeOptionText: {
        ...(TYPOGRAPHY.caption as TextStyle),
        color: COLORS.textLight,
        fontSize: 10,
    },
    imageResizeOptionTextSelected: {
        color: COLORS.primary,
        fontWeight: "700",
    },

    // DATE TIME PICKER STYLES
    dateTimeContainer: {
        flexDirection: 'row',
        gap: 10,
        alignItems: 'center',
    },
    dateTimeInputContainer: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#F8F9FA",
        borderRadius: 14,
        paddingHorizontal: 12,
        height: 52,
    },
    dateTimeInputContainer2: {
        flex: 1.5,
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#F8F9FA",
        borderRadius: 14,
        paddingHorizontal: 12,
        height: 52,
    },
    dateTimeInputContainerButton: {
        width: 52,
        height: 52,
        borderRadius: 14,
        backgroundColor: COLORS.primary,
        justifyContent: "center",
        alignItems: "center",
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 4,
    },
    dateTimeInput: {
        backgroundColor: COLORS.white,
    },

    // MultiSelect overrides
    multiSelectContainer: {
        marginBottom: 20,
    },
    inputContainer2: {
        backgroundColor: "#F8F9FA",
        borderRadius: 14,
        borderWidth: 0,
        paddingHorizontal: 8,
    },
    inputContainer3: {
        backgroundColor: COLORS.white,
    },
    inputContainer4: {
        backgroundColor: "#F8F9FA",
        borderRadius: 14,
        borderWidth: 0,
        height: 52,
    },
});

export default styles;
