import { COLORS } from "@/constants/colors";
import { TYPOGRAPHY } from "@/constants/typography";
import { StyleSheet, type TextStyle } from "react-native";

const styles = StyleSheet.create({
    avatar: {
        width: 36,
        height: 36,
        borderRadius: 18,
        marginRight: 10,
    },
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
        padding: 16,
        paddingBottom: 0,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: COLORS.background,
    },
    profileHeader: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: COLORS.cardBackground,
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        shadowColor: COLORS.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    profileImage: {
        width: 80,
        height: 80,
        borderRadius: 40,
        marginRight: 16,
    },
    profileInfo: {
        flex: 1,
    },
    username: {
        ...(TYPOGRAPHY.h3 as TextStyle),
        color: COLORS.text,
        marginBottom: 4,
    },
    email: {
        ...(TYPOGRAPHY.bodySmall as TextStyle),
        color: COLORS.textLight,
        marginBottom: 4,
    },
    memberSince: {
        ...(TYPOGRAPHY.caption as TextStyle),
        fontSize: 10,
        color: COLORS.textLight,
    },
    logoutButton: {
        backgroundColor: COLORS.white,
        borderRadius: 12,
        padding: 12,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        width:50,
        marginVertical: 8,
        marginHorizontal: 8,
        shadowColor: COLORS.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    logoutText: {
        color: COLORS.white,
        ...(TYPOGRAPHY.label as TextStyle),
        marginLeft: 8,
    },
    booksHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 16,
    },
    booksTitle: {
        ...(TYPOGRAPHY.h3 as TextStyle),
        fontSize: 18,
        color: COLORS.text,
    },
    booksCount: {
        ...(TYPOGRAPHY.bodySmall as TextStyle),
        color: COLORS.textLight,
    },
    booksList: {
        paddingBottom: 20,
    },
    bookItem: {
        flexDirection: "row",
        backgroundColor: COLORS.cardBackground,
        borderRadius: 12,
        padding: 12,
        marginBottom: 12,
        shadowColor: COLORS.shadow,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    bookImage: {
        width: 70,
        height: 100,
        borderRadius: 8,
        marginRight: 12,
    },
    bookInfo: {
        flex: 1,
        justifyContent: "space-between",
    },
    bookTitle: {
        ...(TYPOGRAPHY.label as TextStyle),
        fontSize: 16,
        color: COLORS.text,
        marginBottom: 4,
    },
    ratingContainer: {
        flexDirection: "row",
        marginBottom: 4,
    },
    bookCaption: {
        ...(TYPOGRAPHY.bodySmall as TextStyle),
        color: COLORS.text,
        marginBottom: 4,
        flex: 1,
    },
    bookDate: {
        ...(TYPOGRAPHY.caption as TextStyle),
        fontSize: 11,
        color: COLORS.textLight,
    },
    deleteButton: {
        padding: 8,
        justifyContent: "center",
    },
    emptyContainer: {
        alignItems: "center",
        justifyContent: "center",
        padding: 40,
        marginTop: 20,
    },
    emptyText: {
        ...(TYPOGRAPHY.h3 as TextStyle),
        fontSize: 16,
        color: COLORS.text,
        marginTop: 16,
        marginBottom: 20,
        textAlign: "center",
    },
    addButton: {
        backgroundColor: COLORS.primary,
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 20,
        shadowColor: COLORS.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    addButtonText: {
        color: COLORS.white,
        ...(TYPOGRAPHY.label as TextStyle),
    },
});

export default styles;
